task: "классификация отзывов на книги"

sources:
  - type: hf_dataset
    name: amazon_polarity
    split: train
    sample: 1500
    label_map:
      0: "negative"
      1: "positive"

  - type: hf_dataset
    name: sst2
    split: train
    sample: 500
    text_col: sentence
    label_map:
      0: "negative"
      1: "positive"
